// Generated by 'dotnet new webapi --use-controllers'
// Paul Hammant DevOps, (c) 2018
namespace MyCompany;

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);
        builder.Services.AddControllers();

        var app = builder.Build();
        app.MapControllers();

        app.Run();
    }
}
